### PR TITLE
Implement galaxy planet activity logic

### LINKED ISSUE #204: Implement planet activity logic
Implement planet activity logic indicator that shows on the galaxy and espionage report interface whether the planet has seen activity in the last 60 minutes or not.

Activity is determined based on:

- When the player is logged in and switches to a planet the planet is automatically "updated". Updated means the production is calculated and resources are added to the planet. Any finished buildings from the build queue are added to the planet etc.
- When this update happens the planet record field `updated_at` in the database gets updated to the current time. This field can be used to determine the activity.
- When a foreign player sends an espionage probe with espionage mission to another planet, upon arrival, that planet gets updated and then it is deemed "active" as well.

Implement this activity indicator logic in the following places:

- [ ] Galaxy overview
- [ ] Espionage message

See example of what this indicator should look like in the game:

Screenshot 2024-05-25 at 00 28 11

- Red triangle icon means: activity in last 15 minutes
- Orange square with number in it: amount of minutes (when > 15 minutes)
- Nothing: last activity was more than 60 minutes ago.

Espionage mission message:

Screenshot 2024-05-25 at 00 30 57

### PR DESCRIPTION
**Pull request by Jbaukens**
### Merge Request: Implement Planet Activity Logic for Galaxy View

**Overview:**

This merge request introduces new logic to determine and display the activity status of planets in the galaxy view:

- **Planet Activity Status Calculation:**  
  Implemented the `getMinutesSinceLastUpdate()` method to calculate the time difference since the planet was last updated. This method now returns the number of minutes elapsed, which is used to determine the planet's activity status.

- **Activity Status Scenarios:**  
  - **More than 60 minutes:** The planet is inactive.
  - **Between 15 and 60 minutes:** Displays activity with a specified value.
  - **Between 0 and 15 minutes:** Displays recent activity.

**Changes Made:**

- Added `getMinutesSinceLastUpdate()` method to calculate and return the time difference in minutes.
- Implemented logic to determine and return the planet's activity status based on the elapsed time.
- Configure `maxGalaxies` variable using the new admin setting
- Update version to `0.7.0` in `config/app.php`

**Testing:**

- Verified that the `getMinutesSinceLastUpdate()` method calculates the time difference correctly.
- Ensured that the activity status logic works as intended and reflects the correct status on the galaxy view.

**Next Steps:**

- [ ] Code review and merge upon approval.

**Note:**

- Further adjustments may be made based on additional feedback.

**Related Issue:**

- Partially closes #204
- Opens #313

### CODE REVIEW

**Comment by ghost** [comment]
Hi @lanedirt 

I wanted to let you know that I didn't proceed with the espionage part of issue #204 because I believe it would be more effective to create a new story to refactor the espionage message in line with the new design.

Please let me know your thoughts.

**Comment by lanedirt** [comment]
Hi @Jbaukens,

Thanks for the PR! The code changes as-is look good to me, no comments!

Also thanks for updating the version in `config/app.php`. I honestly forgot that I added that parameter and have since forgotten to increment it since version 0.2.0. I have opened up issue #320 to create a proper release document so myself and/or other maintainers in the future won't forget to update it in the future. 😄 

> I wanted to let you know that I didn't proceed with the espionage part of issue #204 because I believe it would be more effective to create a new story to refactor the espionage message in line with the new design.
> 
> Please let me know your thoughts.

Yes, it's too bad the design changed. For a little bit of background: after I finished implementing the original message system and espionage report templates, it was literally just a few days after that that the official OGame updated and introduced the new message system. I was not expecting that after all those years of the same design haha. If only I waited a few days before implementing it we would already have the new system 😢. Changing all the templates and UI again will indeed be some extra work.

For now though I think it's beneficial to focus on making sure all technical parts of the existing message templates work. Then at a later time we can refactor the designs and can (hopefully) reuse all the back-end code.

So in this case my suggestion would be to update the existing espionage report message and make the `Activity: 60 minutes ago.` text show the planet activity at time of the espionage report creation. With this addition we can then close #204. For the full message system design refactor we can create a new issue to follow up on in the future.

Do you think you could include this change to this PR?  If not, I'm also happy to merge this PR as-is and we can extract this part of #204 to a new issue to take on separately. Please let me know what you think.

**Comment by ghost** [comment]
Hi @lanedirt 

Thats was i understood when i readed the README. Its stated you wanted to keep it as close as possible to the version pre-lifeforms (2020) and features like that and i have of course no access to old styling.

I will add the logic to the espionage report. Just be aware i don't know except for the color and the string, if there were any specific html tags used to represent an activity status.

**Comment by ghost** [comment]
Hi just to let you know, didnt forget you, quit some pressure on work, will be resolved by the weekend

**Comment by lanedirt** [comment]
> Hi just to let you know, didnt forget you, quit some pressure on work, will be resolved by the weekend

Ok thanks for the update. 👍 But don't feel rushed! Life and work comes first. 😄 It will be done when it's done.

**Comment by lanedirt** [comment]
Hi @Jbaukens,

I hope everything's good. Did you have time already to look at the proposed changes? 

I would like to make a new release in the coming days. If you don't have time then no worries, in that case my suggestion would be that I merge the changes as-is and create a new issue to update the messages later.

**Comment by lanedirt** [comment]
> Hi @Jbaukens,
> 
> I hope everything's good. Did you have time already to look at the proposed changes?
> 
> I would like to make a new release in the coming days. If you don't have time then no worries, in that case my suggestion would be that I merge the changes as-is and create a new issue to update the messages later.

I fixed the merge conflicts due to other commits made recently. Merging this as-is as proposed in my previous message. Thanks again for the work @Jbaukens 🚀 , this feature will be included in the upcoming release that I'm preparing now.

I created #378 to continue the work for adding the planet activity to the espionage mission message.

**Pull request merged**
