### PR TITLE
Implement the application tab in the ? pop-up

### LINKED ISSUE #151: Implement "?" popup Applications tab
Implement the logic so the applications tab for the technology popup works. 

See `resources/views/ingame/techtree/applications.blade.php`.

It should look like this:

Screenshot 2024-05-14 at 08 09 44

Screenshot 2024-05-14 at 08 11 27

### PR DESCRIPTION
**Pull request by Chewbaka69**
resolve #151

### CODE REVIEW

**Comment by lanedirt** [comment]
Thanks for the contribution!

I tested this branch and two things that stand out to me:

1) In the official game it shows a red border around a GameObject if the requirements are currently not met. However it doesn't seem to work correctly for me. Below an example, I cannot build Terraformer as shown by the facilities page, but it shows as a green border in the popup. I would expect the terraformer to be greyed out and have a red border.
Screenshot 2024-05-21 at 18 59 02

2) Shipyard "?" popup does not show interplanetary missiles as requirement. In the official game the shipyard includes the interplanetary missiles as a requirement. But it's missing from the list for me. I'm not sure if this is a bug in the code or if a requirement is missing somewhere. I already noticed I made a few mistakes with the initial entry of the game objects, so might be my mistake as well. 😸 
Screenshot 2024-05-21 at 19 05 29

**Comment by Chewbaka69** [comment]
Oooh good catch, i fix the way to have the green border, but maybe i break something else, i will check again :)

**Comment by Chewbaka69** [comment]
some defense and station had the wrong requirement so i fix it, and i rework the method to check the requirement.

**Comment by lanedirt** [comment]
Nice, looks good. Just tested it and as far as I can see it works beautifully now. Awesome! 🏆

**Pull request merged**
